GuitarShop/Controllers/AdminCategoryController.cs
using GuitarShop.Data;
using GuitarShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminCategoryController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        public AdminCategoryController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        public IActionResult List()
        {
            var categories = _repo.Category.FindAll()
                .OrderBy(c => c.CategoryName).ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("AddUpdate", new Category());
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.Action = "Update";
            var category = _repo.Category.GetById(id);
            return View("AddUpdate", category);
        }

        [HttpPost]
        public IActionResult Update(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.CategoryID == 0)
                {
                    _repo.Category.Create(category);
                    TempData["Message"] = $"{category.CategoryName} has been added";
                }
                else
                {
                    _repo.Category.Update(category);
                    TempData["Message"] = $"{category.CategoryName} has been updated";
                }
                _repo.Save();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                return View("AddUpdate");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Category category = _repo.Category.GetById(id);
            return View(category);
        }


        [HttpPost]
        public IActionResult Delete(Category category)
        {
            _repo.Category.Delete(category);
            TempData["Message"] = $"{category.CategoryName} has been deleted";
            _repo.Save();
            return RedirectToAction("List");
        }
    }
}

GuitarShop/Controllers/AdminHomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    [Authorize (Roles ="Administrator")]
    public class AdminHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GuitarShop/Controllers/AdminProductController.cs
using GuitarShop.Data;
using GuitarShop.Models;
using GuitarShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminProductController : Controller
    {
        private readonly IEnumerable<Category> _categories;
        private readonly IRepositoryWrapper _repo;

        public AdminProductController(IRepositoryWrapper repo)
        {
            _repo = repo;
            _categories = _repo.Category.FindAll()
                .OrderBy(c => c.CategoryName);
        }

        public IActionResult List(string id = "all")
        {
            IEnumerable<Product> products;
            if (id == "all")
            {
                products = _repo.Product.FindAll()
                    .OrderBy(p => p.Name);
            }
            else
            {
                products = _repo.Product.GetAllProductsWithCategoryDetails()
                    .Where(p => p.Category.CategoryName.ToLower() == id.ToLower())
                    .OrderBy(p => p.Name);
            }

            var model = new ProductListViewModel
            {
                //Categories = _categories,
                Products = products,
                SelectedCategory = id
            };

            // bind products to view
            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            // create new Product object
            Product product = new();

            // add Category object - prevents validation problem
            product.Category = _repo.Category.GetById(1);  

            // use ViewBag to pass action and category data to view
            ViewBag.Action = "Add";
            ViewBag.Categories = _categories;

            // bind product to AddUpdate view
            return View("AddUpdate", product);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            // get Product object for specified primary key
            Product product = _repo.Product.GetById(id);

            // use ViewBag to pass action and category data to view
            ViewBag.Action = "Update";
            ViewBag.Categories = _categories;

            // bind product to AddUpdate view
            return View("AddUpdate", product);
        }

        [HttpPost]
        public IActionResult Update(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ProductID == 0) // new product
                {
                    _repo.Product.Create(product);
                    TempData["Message"] = $"{product.Name} has been added";
                }
                else  // existing product
                {
                    _repo.Product.Update(product);
                    TempData["Message"] = $"{product.Name} has been updated";
                }
                _repo.Save();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                ViewBag.Categories = _categories;
                return View("AddUpdate", product);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Product product = _repo.Product.GetById(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(Product product)
        {
            _repo.Product.Delete(product);
            TempData["Message"] = $"{product.Name} has been deleted";
            _repo.Save();
            return RedirectToAction("List");
        }
    }
}

GuitarShop/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout";
    string controller =
        ViewContext.RouteData.Values["controller"].ToString().ToLower();
    string action =
        ViewContext.RouteData.Values["action"].ToString().ToLower();
}
<div id="AdminHeader">
    <hr />
    <h2>Guitar Shop Admin</h2>
    <hr />
    <div class="mb-3">
        <a class="@(controller == "adminhome" ? "fw-bold" : "")"
           asp-controller="AdminHome" asp-action="Index">Admin Home</a> |
        <a class="@(controller == "adminproduct" ? "fw-bold" : "")"
           asp-controller="AdminProduct" asp-action="List">Products</a> |
        <a class="@(controller == "admincategory" ? "fw-bold" : "")"
           asp-controller="AdminCategory" asp-action="List">Categories</a>
    </div>
</div>

<div>
    @RenderBody()
</div>

GuitarShop/Views/Shared/_Layout.cshtml
@{
    string controller =
        ViewContext.RouteData.Values["controller"].ToString();
    string action =
        ViewContext.RouteData.Values["action"].ToString();
}
<!DOCTYPE html>
@* Add your personal details here *@
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Guitar Shop</title>
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-href-include="/css/custom.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
            <a class="navbar-brand" href="/">My Guitar Shop</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <nav class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav me-auto">
                    <a class="nav-link
                        @(controller == "Home" && action == "Index" ? "active" : "")"
                       asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-link
                        @(controller == "Product" ? "active" : "")"
                       asp-controller="Product" asp-action="List">Products</a>
                    <a class="nav-link
                        @(controller == "Home" && action == "About" ? "active" : "")"
                       asp-controller="Home" asp-action="About">About</a>
                </div>

                <ul class="navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-link"> 
                            Hello, @User.Identity.Name
                            <img profile-user="@User.Identity.Name" />
                        </li>
                        @if(User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link
                                @(controller.StartsWith("Admin") ? "active" : "")"
                                   asp-controller="AdminHome" asp-action="Index">Admin</a>
                            </li>
                        }
                        
                        <li class="nav-item">
                            <form asp-controller="Account" asp-action="Logout" method="post">

                                <button class="btn btn-link nav-link" type="submit">Log Out</button>

                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Log in</a>
                        </li>
                    }
                </ul>
            </nav>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        <hr />
        <p>&copy; @DateTime.Now.Year - Guitar Shop</p>
    </footer>

    <script asp-src-include="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>