GuitarShop/Components/CategoryMenuViewComponent.cs
using GuitarShop.Data;
using GuitarShop.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private IRepositoryWrapper _repo;
        public CategoryMenuViewComponent(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _repo.Category.FindAll(),
                SelectedCategory = (string)RouteData?.Values["id"]
            };
            return View(model);
        }
    }
}

GuitarShop/Controllers/AdminProductController.cs
using GuitarShop.Data;
using GuitarShop.Models;
using GuitarShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GuitarShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminProductController : Controller
    {
        private readonly IEnumerable<Category> _categories;
        private readonly IRepositoryWrapper _repo;

        public AdminProductController(IRepositoryWrapper repo)
        {
            _repo = repo;
            _categories = _repo.Category.FindAll()
                .OrderBy(c => c.CategoryName);
        }

        public IActionResult List(string id = "all")
        {
            IEnumerable<Product> products;
            if (id == "all")
            {
                products = _repo.Product.FindAll()
                    .OrderBy(p => p.Name);
            }
            else
            {
                products = _repo.Product.GetAllProductsWithCategoryDetails()
                    .Where(p => p.Category.CategoryName.ToLower() == id.ToLower())
                    .OrderBy(p => p.Name);
            }

            var model = new ProductListViewModel
            {
                //Categories = _categories,
                Products = products,
                SelectedCategory = id
            };

            // bind products to view
            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            // create new Product object
            Product product = new();

            // add Category object - prevents validation problem
            product.Category = _repo.Category.GetById(1);  

            // use ViewBag to pass action and category data to view
            ViewBag.Action = "Add";
            ViewBag.Categories = _categories;

            // bind product to AddUpdate view
            return View("AddUpdate", product);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            // get Product object for specified primary key
            Product product = _repo.Product.GetById(id);

            // use ViewBag to pass action and category data to view
            ViewBag.Action = "Update";
            ViewBag.Categories = _categories;

            // bind product to AddUpdate view
            return View("AddUpdate", product);
        }

        [HttpPost]
        public IActionResult Update(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ProductID == 0) // new product
                {
                    _repo.Product.Create(product);
                    TempData["Message"] = $"{product.Name} has been added";
                }
                else  // existing product
                {
                    _repo.Product.Update(product);
                    TempData["Message"] = $"{product.Name} has been updated";
                }
                _repo.Save();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                ViewBag.Categories = _categories;
                return View("AddUpdate", product);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Product product = _repo.Product.GetById(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(Product product)
        {
            _repo.Product.Delete(product);
            TempData["Message"] = $"{product.Name} has been deleted";
            _repo.Save();
            return RedirectToAction("List");
        }
    }
}

GuitarShop/Views/AdminProduct/AddUpdate.cshtml
<!-- this view is used for the Add action and the Update action -->
@model Product
@{
    Layout = "_AdminLayout";
    string title = ViewBag.Action + " Product";
    ViewBag.Title = title;    // sets title to "Add Product" or "Update Product"
}

<h1>@ViewBag.Title</h1>

<form asp-action="Update" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="CategoryID">Category</label>
        <select asp-for="CategoryID"
                asp-items="@(new SelectList(ViewBag.Categories,
                         "CategoryID", "CategoryName",
                         Model.CategoryID.ToString()))"
                class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="Code">Code</label>
        <input asp-for="Code" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input asp-for="Price" class="form-control">
    </div>

    <input type="hidden" asp-for="ProductID" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-action="List" class="btn btn-primary">Cancel</a>
</form>

GuitarShop/Views/AdminProduct/Delete.cshtml
@model Product
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Delete Product";
}

<h1>Confirm Deletion</h1>
<h3>@Model.Name</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="ProductID" />
    <input type="hidden" asp-for="Name" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-action="List" class="btn btn-primary">Cancel</a>
</form>

GuitarShop/Views/AdminProduct/List.cshtml
@model ProductListViewModel
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Product Manager";
}

<h1>@ViewBag.Title</h1>

@if (TempData["Message"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="btn-close" 
                data-bs-dismiss="alert" aria-label="Close">
        </button>
        @TempData["Message"]
    </div>
}

<div class="row">
    <div class="col-sm-2">
        <vc:category-menu></vc:category-menu>
    </div>

    <div class="col-sm-10">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th class="text-end">Price</th>
                    <th></th>
                    <th></th>
            </thead>
            <tbody>
                @foreach (var p in Model.Products)
                {
                    <tr>
                        <td>@p.Name</td>
                        <td class="text-end">@p.Price.ToString("C")</td>
                        <td>
                            <a asp-action="Update"
                           asp-route-id="@p.ProductID">Update</a>
                        </td>
                        <td>
                            <a asp-action="Delete"
                           asp-route-id="@p.ProductID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-action="Add" class="btn btn-primary">Add New Product</a>
    </div>
</div>